name: ipaintokc
favicon: null
layout_spectrum: 0.26821
typography_spectrum: 0.50221
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: iPaint
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B3B3B3'
    - '#FFFFFF'
    - '#7EBEC5'
    - '#2B3A3C'
    - '#888889'
  brandStrength: 0.6816009
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
