name: ipaintokc
favicon: null
layout_spectrum: 0.5434383382089436
typography_spectrum: 0.070248335134238
title: Oklahoma City Paint Contractor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5777248493395746
  lightness: 0.5694621987640858
  saturation: 0.867252757307142
  rhythmicContrast: 0.3912595175206661
purpose: []
